version: "3.2"

# SERVICES
services:

  # NGINX
  jenkins-nginx:
    image: "ricardoalcazar/nginx:latest"
    depends_on:
      - jenkins
      - cadvisor
    ports:
      - "80:80"
    networks:
      - jenkins-nginx-service-network
    deploy:
      placement:
        constraints: [node.role == manager]      

  # JENKINS MASTER
  jenkins:
    image: "ricardoalcazar/jenkins:lts"
    ports:
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
    networks:
      - jenkins-nginx-service-network
    deploy:
      placement:
        constraints: [node.role == manager]

  # CADVISOR
  cadvisor:
    image: "google/cadvisor"
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      - jenkins-nginx-service-network

# NETWORKS
networks:
  jenkins-nginx-service-network:

# VOLUMES
volumes:
  jenkins:
    external:
      name: jenkins-nginx-service


