version: "3.2"

# SERVICES
services:

  # NGINX
  jenkins-nginx:
    image: "ricardoalcazar/nginx:latest"
    depends_on:
      - jenkins
    ports:
      - "80:80"
    networks:
      - jenkins-nginx-service-network
    deploy:
      placement:
        constraints: [node.role == manager]      

  # JENKINS MASTER
  jenkins:
    image: "ricardoalcazar/jenkins:lts"
    ports:
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
    networks:
      - jenkins-nginx-service-network
    deploy:
      placement:
        constraints: [node.role == manager]

# NETWORKS
networks:
  jenkins-nginx-service-network:

# VOLUMES
volumes:
  jenkins:
    external:
      name: jenkins-nginx-service


