version: "3.2"

# SERVICES
services:

  # NGINX
  jenkins-nginx:
    deploy:
      placement:
        constraints: [node.role == manager]

  # JENKINS MASTER
  jenkins:
    deploy:
      placement:
        constraints: [node.role == manager]



