version: "3.2"

# SERVICES
services:

  # LOAD BALANCER
  jenkins-loadbalancer:
    image: dockercloud/haproxy
    depends_on:
      - jenkins
      - jenkins-nginx
    environment:
      - BALANCE=leastconn
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "2375:2375"
    networks:
      - jenkins-proxy-network
    deploy:
      placement:
        constraints: [node.role == manager]


  # PROXY
  jenkins-proxy:
    image: "ricardoalcazar/jenkins-proxy:latest"
    depends_on:
      - jenkins
    command: "-i"
    environment:
      - SERVICE_PORTS=2375
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jenkins-proxy-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      #placement:
      #  constraints: [node.role == worker]  

  # NGINX
  jenkins-nginx:
    image: "ricardoalcazar/nginx:latest"
    depends_on:
      - jenkins
    ports:
      - "80:80"
    networks:
      - jenkins-proxy-network
    deploy:
      placement:
        constraints: [node.role == manager]      

  # JENKINS MASTER
  jenkins:
    image: "ricardoalcazar/jenkins:lts-plugins"
    ports:
      #- "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
    networks:
      - jenkins-proxy-network
    deploy:
      placement:
        constraints: [node.role == manager]

# NETWORKS
networks:
  jenkins-proxy-network:

# VOLUMES
volumes:
  jenkins:
    external:
      name: jenkins-nginx-service


