version: "3.2"

# SERVICES
services:

  # PROXY
  jenkins-proxy:
    image: "ricardoalcazar/jenkins-proxy:latest"
    depends_on:
      - jenkins
    command: "-i"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - jenkins-proxy-network
    deploy:
      #mode: global
      #endpoint_mode: dnsrr
      placement:
        constraints: [node.role == worker]  

  # NGINX
  jenkins-nginx:
    image: "ricardoalcazar/nginx:latest"
    depends_on:
      - jenkins
    ports:
      - "80:80"
    networks:
      - jenkins-proxy-network
    deploy:
      placement:
        constraints: [node.role == manager]      

  # JENKINS MASTER
  jenkins:
    image: "ricardoalcazar/jenkins:lts-plugins"
    ports:
      #- "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
    networks:
      - jenkins-proxy-network
    deploy:
      placement:
        constraints: [node.role == manager]

# NETWORKS
networks:
  jenkins-proxy-network:

# VOLUMES
volumes:
  jenkins:
    external:
      name: jenkins-nginx-service


